### PR TITLE
urlsplit back compatibility with python 2.4

### PR DESCRIPTION
**Pull request by alda519**
fixing bug introduced in dc7ee6d

      File "/usr/share/rhn/up2date_client/rpcServer.py", line 75, in _request1
        typ = parse_res.scheme
    exceptions.AttributeError: 'tuple' object has no attribute 'scheme'

### CODE REVIEW

**Comment by jiridostal** [comment]
baaf6a971c6c3ddc1c5faf5501c1ddaf0d885fc2
